version: '3.8'
services:

  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8081:5432"
    volumes:
      - db:/var/lib/postgresql/data

  binance-parser-service:
    image: binance-parser-service:latest
    restart: always
    env_file: ENV/binance-parser-service.env
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  db:
    driver: local